services:
  paperforge:
    # image: ghcr.io/sergiors/paperforge:latest
    build:
      context: .
    container_name: paperforge
    platform: linux/amd64
    environment:
      - LOG_LEVEL=INFO
      - TZ=Europe/Rome
    ports:
      - 8000:8000
